# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/Desktop/Video_new_PCB/PCB_test_project/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/ADV7611_LLC/ADV7611_LLC.xci
# IP: The module: 'ADV7611_LLC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Desktop/Video_new_PCB/PCB_test_project/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/ADV7611_LLC/ADV7611_LLC_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADV7611_LLC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/Desktop/Video_new_PCB/PCB_test_project/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/ADV7611_LLC/ADV7611_LLC.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADV7611_LLC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/Desktop/Video_new_PCB/PCB_test_project/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/ADV7611_LLC/ADV7611_LLC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADV7611_LLC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: h:/Desktop/Video_new_PCB/PCB_test_project/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/ADV7611_LLC/ADV7611_LLC.xci
# IP: The module: 'ADV7611_LLC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Desktop/Video_new_PCB/PCB_test_project/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/ADV7611_LLC/ADV7611_LLC_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADV7611_LLC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/Desktop/Video_new_PCB/PCB_test_project/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/ADV7611_LLC/ADV7611_LLC.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADV7611_LLC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/Desktop/Video_new_PCB/PCB_test_project/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/ADV7611_LLC/ADV7611_LLC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADV7611_LLC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
