# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/Desktop/Code_copy/PCB_test_60fps_1/PCB_test.srcs/sources_1/ip/Video_in_ram/Video_in_ram.xci
# IP: The module: 'Video_in_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Desktop/Code_copy/PCB_test_60fps_1/PCB_test.srcs/sources_1/ip/Video_in_ram/Video_in_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Video_in_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: H:/Desktop/Code_copy/PCB_test_60fps_1/PCB_test.srcs/sources_1/ip/Video_in_ram/Video_in_ram.xci
# IP: The module: 'Video_in_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Desktop/Code_copy/PCB_test_60fps_1/PCB_test.srcs/sources_1/ip/Video_in_ram/Video_in_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Video_in_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
