# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/Desktop/PCB_test_DDR3_30fps_1/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/DDR_out_distribute_ram/DDR_out_distribute_ram.xci
# IP: The module: 'DDR_out_distribute_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Desktop/PCB_test_DDR3_30fps_1/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/DDR_out_distribute_ram/DDR_out_distribute_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR_out_distribute_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: h:/Desktop/PCB_test_DDR3_30fps_1/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/DDR_out_distribute_ram/DDR_out_distribute_ram.xci
# IP: The module: 'DDR_out_distribute_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Desktop/PCB_test_DDR3_30fps_1/PCB_test_DDR3_ok1/PCB_test/PCB_test.srcs/sources_1/ip/DDR_out_distribute_ram/DDR_out_distribute_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR_out_distribute_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
